// packages/widget-core/packages/demo/src/App.svelte
<script lang="ts">
	import "../../lib";

	let themeScheme = "light";
	let position = "right";
	let primaryColor = "#1677ff";
	let textColor = "#171717";
	let backgroundColor = "#fafafa";

	$: {
		document.documentElement.classList.toggle("dark", themeScheme === "dark");
	}

	$: {
		if (themeScheme === "light") {
			textColor = "#171717";
			backgroundColor = "#fafafa";
		} else {
			textColor = "#ededed";
			backgroundColor = "#000000";
		}
	}
</script>

<main>
	<fieldset>
		<legend>Theme:</legend>

		<div>
			<input type="radio" id="light" name="theme" value="light" checked bind:group={themeScheme} />
			<label for="light">Light</label>

			<input type="radio" id="dark" name="theme" value="dark" bind:group={themeScheme} />
			<label for="dark">Dark</label>
		</div>

		<div>
			<div>
				<input type="color" id="primaryColor" bind:value={primaryColor} />
				<label for="primaryColor">Primary Color</label>
			</div>

			<div>
				<input type="color" id="backgroundColor" bind:value={backgroundColor} />
				<label for="backgroundColor">Background Color</label>

				<input type="color" id="textColor" bind:value={textColor} />
				<label for="textColor">Text Color</label>
			</div>
		</div>
	</fieldset>
	<fieldset>
		<legend>Positon:</legend>

		<div>
			<input type="radio" id="right" name="position" value="right" checked bind:group={position} />
			<label for="right">Right</label>

			<input type="radio" id="left" name="position" value="left" bind:group={position} />
			<label for="left">Left</label>
		</div>
	</fieldset>

	<img class={`arrow arrow-${position} arrow-${themeScheme}`} src="/arrow.svg" alt="Arrow" />

	<feedbacky-widget
		project-id="b4dbbce7-92ae-47fa-840e-b696a9fb856b"
		theme-scheme={themeScheme}
		theme-primary-color={primaryColor}
		theme-text-color={textColor}
		theme-background-color={backgroundColor}
		meta-customerId="123"
		meta-role="manager"
		{position}
	/>
</main>

// apps/example-react/src/App.tsx
import { useEffect, useState } from "react";
import { Feedbacky } from "@feedbacky/widget-react";

import arrowLogo from "./assets/arrow.svg";

function App() {
  const [scheme, setScheme] = useState<"light" | "dark">("light");
  const [position, setPosition] = useState<"right" | "left">("right");
  const [primaryColor, setPrimaryColor] = useState("#1677ff");
  const [textColor, setTextColor] = useState("#171717");
  const [backgroundColor, setBackgroundColor] = useState("#fafafa");

  useEffect(() => {
    document.documentElement.classList.toggle("dark", scheme === "dark");

    if (scheme === "light") {
      setTextColor("#171717");
      setBackgroundColor("#fafafa");
    } else {
      setTextColor("#ededed");
      setBackgroundColor("#000000");
    }
  }, [scheme]);

  const onSchemeChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setScheme(e.target.value as "light" | "dark");
  };

  const onPositionChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setPosition(e.target.value as "right" | "left");
  };

  return (
    <main>
      <fieldset>
        <legend>Theme:</legend>

        <div>
          <input
            type="radio"
            id="light"
            name="theme"
            value="light"
            checked={scheme === "light"}
            onChange={onSchemeChange}
          />
          <label htmlFor="light">Light</label>

          <input
            type="radio"
            id="dark"
            name="theme"
            value="dark"
            checked={scheme === "dark"}
            onChange={onSchemeChange}
          />
          <label htmlFor="dark">Dark</label>
        </div>

        <div>
          <div>
            <input
              type="color"
              id="primaryColor"
              value={primaryColor}
              onChange={(e) => setPrimaryColor(e.target.value)}
            />
            <label htmlFor="primaryColor">Primary Color</label>
          </div>

          <div>
            <input
              type="color"
              id="backgroundColor"
              value={backgroundColor}
              onChange={(e) => setBackgroundColor(e.target.value)}
            />
            <label htmlFor="backgroundColor">Background Color</label>

            <input
              type="color"
              id="textColor"
              value={textColor}
              onChange={(e) => setTextColor(e.target.value)}
            />
            <label htmlFor="textColor">Text Color</label>
          </div>
        </div>
      </fieldset>
      <fieldset>
        <legend>Positon:</legend>

        <div>
          <input
            type="radio"
            id="right"
            name="position"
            value="right"
            checked={position === "right"}
            onChange={onPositionChange}
          />
          <label htmlFor="right">Right</label>

          <input
            type="radio"
            id="left"
            name="position"
            value="left"
            checked={position === "left"}
            onChange={onPositionChange}
          />
          <label htmlFor="left">Left</label>
        </div>
      </fieldset>

      <img
        className={`arrow arrow-${position} arrow-${scheme}`}
        src={arrowLogo}
        alt="Arrow"
      />

      <Feedbacky
        projectId="24320d3d-c5f2-44e1-83a1-13e1cb61fe1d"
        position={position}
        theme={{
          scheme,
          primaryColor,
          textColor,
          backgroundColor,
        }}
        meta={{
          customerId: "123",
          role: "admin",
        }}
      />
    </main>
  );
}

export default App;
